# OrangeFox BoardConfig
DEVICE_PATH := device/infinix/X655C
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := armeabi-v7a
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53

TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := true

# Platform
TARGET_BOARD_PLATFORM := mt6765
TARGET_BOOTLOADER_BOARD_NAME := CY-X655C-H6211-

# Filesystem
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_SCREEN_DENSITY := 320
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive androidboot.boot_devices=bootdevice androidboot.hardware=mt6765 androidboot.logical_partitions=1
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_KERNEL_IMAGE_NAME := Image.gz
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x11a88000
BOARD_KERNEL_TAGS_OFFSET := 0x07808000
BOARD_KERNEL_PAGESIZE := 2048

TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 40894464
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_SIZE := 629145600
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 524288000
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_USERDATAIMAGE_PARTITION_SIZE := 119291231232

TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_USES_DRM_HWCOMPOSER := true

# Dynamic Partitions
BOARD_SUPER_PARTITION_SIZE := 4479516672
BOARD_SUPER_PARTITION_GROUPS := infinix_dynamic_partitions
BOARD_INFINIX_DYNAMIC_PARTITIONS_SIZE := 4475322368
BOARD_INFINIX_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product
BOARD_USES_DYNAMIC_PARTITIONS := true

# MTK
BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true

# AVB
BOARD_AVB_ENABLE := false
OF_PATCH_AVB20 := 1
BOARD_USES_METADATA_PARTITION := true
BUILD_BROKEN_VNDK_VERSION := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# Security
VENDOR_SECURITY_PATCH := 2020-03-05
PLATFORM_SECURITY_PATCH := 2020-03-05
PLATFORM_VERSION := 10

# OrangeFox Specific
OF_USE_TWRP := 1
OF_NO_TWRP_COMPAT := 0
OF_PATCH_VARIANT := t33xx
OF_MAINTAINER := Hylassx
FOX_VERSION := 12.1

# Other
OF_ENABLE_LPTOOLS := 1
OF_FIX_DECRYPTION_ON_DATA_MEDIA := 1
OF_NO_KEYMASTER_VER_4X := 1
OF_DEFAULT_KEYMASTER_VERSION := 4.0

OF_SCREEN_H := 1600
OF_STATUSBAR_H := 60
OF_STATUSBAR_W := 720
OF_PADDING_H := 10
OF_FORCE_USE_RECOVERY_FSTAB := 1
OF_THEME := portrait_hdpi
OF_ENABLE_LOGGING := 1
OF_INCLUDE_FASTBOOTD := 1
OF_INCLUDE_RESETPROP := 1
OF_INCLUDE_LIBRESETPROP := 1

# Storage
RECOVERY_SDCARD_ON_DATA := 1
OF_EXCLUDE_DEFAULT_USB_INIT := 1
OF_NO_SCREEN_TIMEOUT := 1

# Brightness
OF_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
OF_DEFAULT_BRIGHTNESS := 25
OF_MAX_BRIGHTNESS := 225
OF_INPUT_BLACKLIST := "hct_battery"

TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1600

# Twrp Spesific
TW_INCLUDE_CRYPTO := false
TW_INCLUDE_CRYPTO_FBE := false
TW_SKIP_ADDITIONAL_FSTAB := true
TW_THEME := portrait_hdpi

# Crypto
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_SKIP_FBE_DECRYPTION := 1
OF_TWRP_COMPATIBILITY_MODE := 1
OF_SKIP_FBE_DECRYPTION_SDKVERSION := 29
OF_EXCLUDE_ENCRYPTED_BACKUPS := 1
OF_INCLUDE_CRYPTO := 1
OF_SELINUX_RELEASE_PERMISSIVE := 1

# Crypto Shared Library Relinking
TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += \
    $(TARGET_OUT_SHARED_LIBRARIES)/libkeymaster_messages.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/libkeymaster_portable.so
